[package]
name = "rust-api"
version = "0.1.0"
authors = ["Richard Anaya <richard.anaya@gmail.com>"]

[dependencies]
aws_lambda = { git = "https://github.com/srijs/rust-aws-lambda" }
serde_json = "1.0"
